services:
  - type: web
    name: blog-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node api/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production